### ISSUE TITLE
Consider using `interruptible`

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-kafka#1]
Instead of:

```scala
blocking(ZIO(...))
```

Consider:

```scala
interruptible(...)
```

Both will be placed on the blocking thread pool, but the latter can be interrupted.

**Comment by iravid** [comment]
@jdegoes Good point! The Kafka consumer can handle thread interruptions, but the docs recommend that `consumer.wakeup()` be used.

So I've used the following effect import function:
```
  def withConsumer[A](c: ByteConsumer)(f: ByteConsumer => A): BlockingTask[A] =
    ZIO.effectAsyncInterrupt[Blocking, Throwable, A] { cb =>
      cb(blocking(ZIO.effect(f(c))).catchSome {
        case _: WakeupException => ZIO.interrupt
      })

      Left(UIO(c.wakeup()))
    }
```

The producer, however, can be interrupted with `Thread.interrupt` but presents an interesting usecase not covered by `effectBlocking` - a blocking function that completes asynchronously. Here's how it is going to be implemented currently:
```
      def produce(record: ByteProducerRecord): BlockingTask[RecordMetadata] =
        for {
          done    <- Promise.make[Throwable, RecordMetadata]
          runtime <- ZIO.runtime[Blocking]
          _ <- effectBlocking {
                p.send(
                  record,
                  new Callback {
                    def onCompletion(metadata: RecordMetadata, err: Exception): Unit = {
                      if (err != null) runtime.unsafeRun(done.fail(err))
                      else runtime.unsafeRun(done.succeed(metadata))

                      ()
                    }
                  }
                )
              }
          recordMetadata <- done.await
        } yield recordMetadata
```
Is there a nicer way of doing this without reaching into the runtime?

**Comment by ghostdogpr** [comment]
@iravid is it really blocking? According to the [javadoc](https://kafka.apache.org/22/javadoc/index.html?org/apache/kafka/clients/producer/KafkaProducer.html), `The send is asynchronous and this method will return immediately once the record has been stored in the buffer of records waiting to be sent. This allows sending many records in parallel without blocking to wait for the response after each one.`

The `get` method does but we're not using it: `If you want to simulate a simple blocking call you can call the get() method immediately`.

Looks like we could use `effectAsync` and simplify this?

**Comment by iravid** [comment]
Yes, normally it won’t block, but when the producer’s buffer is full (due to e.g. broker issues), send will block until the record can be stored in the buffer.

**Comment by ghostdogpr** [comment]
Indeed, it's quite hidden in the doc but `When the buffer space is exhausted additional send calls will block.` 😢

**Comment by iravid** [comment]
@ghostdogpr I do realize though that we should have a `sendChunk(c: Chunk[Record])` method to amortize the cost of `effectBlocking`.

**Comment by iravid** [comment]
Alright, so this is covered.
