### ISSUE TITLE
.retry does not actually restart the stream

### ISSUE THREAD

**Issue by mandrush** [zio/zio-kafka#1003]
I'm trying to fix an issue occuring in our production setup, where sometimes the consumer seemingly just stops consuming, pro-actively leaving the group. This causes the group to re-balance and we get pods that could be still consuming, but aren't because they are paused. 

I tried to replicate this behavior like so:
```scala
  override def run(args: List[String]): URIO[ZEnv, ExitCode] = {
    val program = for {
      _ <- putStrLn(s"Start Kafka Consumer with ${consumerSettings}")
      c <-
        Consumer
          .subscribeAnd(Subscription.topics(topic))
          .plainStream(Serde.string, Serde.string)
          .flatMapPar(parallelism) { rec =>
            if (scala.util.Random.nextInt(140) > 137) {
              ZStream.fail(new RuntimeException("Fatal consumer error"))
            } else {
              ZStream.succeed(rec)
            }
          }
          .retry(Schedule.recurs(3))
          .mapMPar(parallelism)(_ => ZIO.fiberId.flatMap(fiberId => putStrLn(s"fiberId: $fiberId")))         
           .runDrain
          .fork
      res <- c.join
    } yield res
    program.provideLayer(consumer).exitCode
  }
  ```
  (In our case it's not an issue with an uncaught exception being thrown in the chain, but just to provide an example)
  I thought the `retry` function would be enough to just restart the entire consumer stream. However, it seems it's not the case - the consumer sometimes gets restarted, but the partition is still paused and it won't consume the events ever again.

Here's an example debug message that appears after the attempt to retry the entire stream:
```2023-07-27 15:31:41,410 [zio-default-blocking-1] DEBUG o.a.k.c.c.internals.AbstractFetch - [Consumer clientId=consumer-mandrusz-test-1, groupId=mandrusz-test] Skipping fetching records for assigned partition data-5 because it is paused```

To clarify, the behavior I expected was: in case of a retry, the consumer re-attempts to consume the partition from the last committed offset. In akka-streams there was a way to restart the entire stream thanks to supervision strategies provided by the actor system. Is there any way to replicate this restart behavior in zio-kafka? If not, why is the stream not being completely restarted?

We're on `ZIO 1.0.12` and `zio-kafka 0.17.6`

**Comment by svroonland** [comment]
Yeah retry on the plainStream or partitionedStream doesn't work before zio-kafka v2.1, a known limitation.

**Comment by mandrush** [comment]
Thank you for the clarification.
