### ISSUE TITLE
Can we configure the zio-kafka with IAM access control for MSK?

### ISSUE THREAD

**Issue by yanqianglu** [zio/zio-kafka#1064]
Hi all,

We have an Amazon MSK cluster that is behind IAM access check. Here is their documentation about how to setup the java client for secured connections. https://aws.amazon.com/blogs/big-data/securing-apache-kafka-is-easy-and-familiar-with-iam-access-control-for-amazon-msk/. I'm wondering if it's possible to do that kind of setup for zio-kafka.

Thanks,

**Comment by erikvanoosten** [comment]
Hi @yanqianglu . Yes, you can configure and/or override all consumer properties of the underlying standard Java Kafka client. This is done with method `ConsumerSettings.withProperties`.
