### ISSUE TITLE
Unexpected behavior during graceful shutdown

### ISSUE THREAD

**Issue by bsaletti** [zio/zio-kafka#1087]
Hi,

We are observing some unexpected behavior when we do a graceful shutdown on applications running zio-kafka.

What we expected or were hopping to see was that a graceful shutdown would finish processing any messages already in flight but would stop consuming new messages. Once all in flight messages are committed it should shut down the consumer and
cleanup all ressources.

What we are observing is that partitions are reallocated right away and therefore picked up by other instances while some messages are still being processed and are not yet committed.
This results in the same message being processed twice, once in the instance that is shutting down and once in whatever instance gets assigned the partitions.

Could it be that the consumer gets closed too early ?

**Comment by erikvanoosten** [comment]
Thanks for your report. The problem is that zio-kafka does not take into account what the streams are doing.

Right now we are fixing the related problem of preventing duplicates during a rebalance (#830). Once this is in place, it will be fairly straight forward to fix this problem as well.

**Comment by bsaletti-fgh** [comment]
Thank you for your reply, we're waiting for it :)

**Comment by bsaletti** [comment]
I'm testing the commit, the results are pretty nice.
I have a few duplicates (1-10 for 20000 records) but not on the same pod, I think it's on my side.

**Comment by erikvanoosten** [comment]
Duplicated by #1132

**Comment by adeibnugandiSH** [comment]
How are you
