### ISSUE TITLE
Unnecessary jackson-databind dependency

### ISSUE THREAD

**Issue by povder** [zio/zio-kafka#1095]
jackson-databind was added as a dependency of zio-kafka as part of https://github.com/zio/zio-kafka/pull/247 . At that time kafka-client's version used was 2.6.0 and that kafka-clients version declared jackson-databind as `provided` in its POM. Right now, kafka-clients 3.6.0 is used by zio-kafka and 3.x versions don't depend on Jackson anymore (no jackson-databind in their POM). The jackson-databind dependency should then be removed from zio-kafka.

**Comment by erikvanoosten** [comment]
That is really nice finding. Thanks for your report @povder !
