### ISSUE TITLE
Should commitOrRetry also retry commit timeouts?

### ISSUE THREAD

**Issue by fmeeuw** [zio/zio-kafka#1126]
Hi, 

The Offset.commitOrRetry method currently is implemented to only retry `RetriableCommitFailedException` errors, like this:
```
    commit.retry(
      Schedule.recurWhile[Throwable] {
        case _: RetriableCommitFailedException => true
        case _                                 => false
      } && policy
 ```

I was expecting a `zio.kafka.consumer.CommitTimeout` to be also retried, but that currently isn't the case. 
There is of course a simple workaround, to add another .retry after the .commitOrRetry. 
However I think it would be nice if commitOrRetry also retries commit timeouts, what do you think?

**Comment by erikvanoosten** [comment]
Solved by #1140.
