### ISSUE TITLE
`partitionsFor` method missing from `zio.kafka.producer.Producer`

### ISSUE THREAD

**Issue by kyri-petrou** [zio/zio-kafka#1146]
Hi there 👋 

It would be nice if the `Producer` API exposed the `partitionsFor` method which exists in the underlying Java producer. I'm happy to make a PR for if - please let me know if you're happy to add that and I'll submit one

**Comment by erikvanoosten** [comment]
Hi @kyri-petrou, thanks. A PR would be awesome.

**Comment by kyri-petrou** [comment]
@erikvanoosten out of curiosity, when are you planning to release the next version? I'm only asking cause I'd like to use this method and just wondering whether I should wait for the next release or workaround it by initializing the Java client manually

**Comment by erikvanoosten** [comment]
I would like to complete #1143 and then do a release.

**Comment by kyri-petrou** [comment]
Awesome, thanks a lot!
