### ISSUE TITLE
Setup benchmarks

### ISSUE THREAD

**Issue by iravid** [zio/zio-kafka#122]
I've recently ran into some performance issues with the library, so this would be a good time to setup benchmarking infrastructure and benchmarks. Comparisons should be done with the plain Kafka consumer/producer and Alpakka Kafka.

**Comment by svroonland** [comment]
Partially done in #689, a comparison should still be added.

**Comment by guizmaii** [comment]
Comparison benchs initiated here: https://github.com/zio/zio-kafka/pull/695

My goal will be to compare with kafka-clients, monix-kafka and fs2-kafka

**Comment by erikvanoosten** [comment]
Benchmarks are now present. The results are available on https://zio.github.io/zio-kafka/dev/bench/
