### ISSUE TITLE
Partition handling with plainStream and partitionedStream

### ISSUE THREAD

**Issue by petern-sc** [zio/zio-kafka#1239]
Hi, I was tracking down a performance issue with our Kafka consumer and I noticed the difference came from the usage of `plainStream` an `partitionedStream`.

We originally had something along the lines of:
```scala
val maxParallelism = 5
Consumer
    .partitionedStream(Subscription.topics(topicName), Serde.byteArray.asOption, Serde.byteArray.asOption)
    .flatMapPar(maxParallelism) { case (_, stream) => stream.mapZIO(handleRecord) }
    .aggregateAsync(Consumer.offsetBatches)
    .schedule(Schedule.fixed(2.seconds))
    .run(ZSink.foreach(_.commit))
```
Which resulted in very low throughput and the consumer stalling.

When using plainStream, with all else being equal, results in going back to "normal" performance.
```scala
val maxParallelism = 5
Consumer
    .plainStream(Subscription.topics(topicName), Serde.byteArray.asOption, Serde.byteArray.asOption)
    .mapZIOPar(maxParallelism)(handleRecord)
    .aggregateAsync(Consumer.offsetBatches)
    .schedule(Schedule.fixed(2.seconds))
    .run(ZSink.foreach(_.commit))
```

Looking at the implementations, the only difference I can see is that `plainStream` has infinite parallelism when pulling from `partitionedStream`. However I was expected that as a pull stream, when I call `.mapZIOPar(maxParallelism)` this would still bottleneck the records that we pull from `plainStream` so that the performance would be similar.

Is there something I'm misunderstanding in how the 2 methods differ?

Minimal repo to reproduce this: https://github.com/petern-sc/kafka-perf

---
Update:

I realised this wasn't a performance issue but a logic issue. 

With a parallelism of 5, only 5 partitions were being consumed from. The consumer never yields and begins consuming from the other partitions causing Kafka to eventually evict the consumer. Is this behaviour expected from `partitionedStream` ie. partitionedStreams always requires parallelism >= number of partitions for the consumer.

```
kafka-consumer-groups --group test-consumer-1715230505326 --describe --bootstrap-server localhost:9091

GROUP                       TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                               HOST            CLIENT-ID
test-consumer-1715230505326 test-topic-1    38         272832          272832          0               test-e0c3645d-2794-4d6f-9246-37e7f3782735 /192.168.65.1   test
test-consumer-1715230505326 test-topic-1    42         261613          261613          0               test-e0c3645d-2794-4d6f-9246-37e7f3782735 /192.168.65.1   test
test-consumer-1715230505326 test-topic-1    36         260602          260602          0               test-e0c3645d-2794-4d6f-9246-37e7f3782735 /192.168.65.1   test
test-consumer-1715230505326 test-topic-1    48         261082          261082          0               test-e0c3645d-2794-4d6f-9246-37e7f3782735 /192.168.65.1   test
test-consumer-1715230505326 test-topic-1    44         260256          260256          0               test-e0c3645d-2794-4d6f-9246-37e7f3782735 /192.168.65.1   test
test-consumer-1715230505326 test-topic-1    27         -               253734          -               test-e0c3645d-2794-4d6f-9246-37e7f3782735 /192.168.65.1   test
test-consumer-1715230505326 test-topic-1    37         -               266512          -               test-e0c3645d-2794-4d6f-9246-37e7f3782735 /192.168.65.1   test
test-consumer-1715230505326 test-topic-1    8          -               270707          -               test-e0c3645d-2794-4d6f-9246-37e7f3782735 /192.168.65.1   test
test-consumer-1715230505326 test-topic-1    14         -               267647          -               test-e0c3645d-2794-4d6f-9246-37e7f3782735 /192.168.65.1   test
```

**Comment by svroonland** [comment]
> Is this behaviour expected from partitionedStream ie. partitionedStreams always requires parallelism >= number of partitions for the consumer.
If you use mapZIOPar, your max parallelism indeed needs to be equal to or larger than the amount of partitions assigned to that consumer. In general I'd advice to use Int.MaxValue here.

**Comment by petern-sc** [comment]
> In general I'd advice to use Int.MaxValue here
Is it worth calling that out in the docs specifically given it breaks the consumer logic otherwise? I'm happy to raise a PR for that.

**Comment by svroonland** [comment]
Yes that would definitely be a nice addition, happy to accept the PR

**Comment by petern-sc** [comment]
Sorry for the delay, this slipped my mind for a while. Raised https://github.com/zio/zio-kafka/pull/1269
