### ISSUE TITLE
FromJavaConsumer: how to synchronize access to the java consumer

### ISSUE THREAD

**Issue by tnielens** [zio/zio-kafka#1276]
#694 introduced a `fromJavaConsumer` constructor. But it isn't clear how to synchronize access to the consumer once handed to zio-kafka. My use case is the same as the one reported in #694. I have some logic working on the java consumer to check for the consumer lag, health and other metrics. These checks run periodically but I need to coordinate the accesses with zio-kafka. As far as I understand, zio-kafka doens't provide that ability and I'll face concurrency issues if both my checks and zio-kafka run tasks against the consumer concurrently.

**Comment by svroonland** [comment]
zio-kafka protects against concurrent access using a Semaphore. We could perhaps allow the user to pass their own Semaphore in `fromJavaConsumer`. It would need to have at most 1 permit, something we can't guarantee, but it seems reasonable to document this and expect undefined behavior when it's more than 1 permit.

**Comment by erikvanoosten** [comment]
@tnielens What is your use case? Would you be helped if all operations of the java-kafka consumer are available on the zio-kafka consumer?
If not, another option would be to return an implementation of `org.apache.kafka.clients.consumer.Consumer` which wraps the given java consumer and uses the zio-kafka semaphore to synchronize access.

**Comment by tnielens** [comment]
My usecase is passing the kafka consumer to a `HealthCheckService`of mine which is maintained separately and works against the standard `Consumer` class. It checks different things. Among them, metrics like the `last-poll-seconds-ago`, what is the current lag of the consumer, does the lag decrease, etc. 

One workaround I'm trying now is introducing a `class SynchronizedConsumer[K, V](delegate: Consumer[K, V]) extends Consumer[K, V]` which wraps all delegate calls with `synchronized { ... }` except for the `wakeup()`call. Not ideal as zio-kafka's `Consumer` might not expect all calls to the standard `Consumer` to potentially block.

**Comment by erikvanoosten** [comment]
> Not ideal as zio-kafka's Consumer might not expect all calls to the standard Consumer to potentially block.

I think that is okay! The zio-kafka consumer already runs on its own thread because almost every call to the standard consumer blocks! If it blocks a little bit longer, nobody will notice!

**Comment by svroonland** [comment]
This makes me wonder if we should keep `fromJavaConsumer` in this form, since anybody using the provided java consumer would run in to this concurrent access issue at some point. I think my proposal of requiring an externally passed Semaphore would be a good solution. It would be an incompatible change, but we can deprecate the old method.
