### ISSUE TITLE
Serialization throwing defects

### ISSUE THREAD

**Issue by lemony312** [zio/zio-kafka#1331]
I have a case class using zio json.
My message is failing to serialize as a string to due to an accidental null.
The problem is the library causes a defect in the program as opposed to a typed exception.

```
 case class MyMessage(errors: List[String])
  object MyMessage {
    implicit val decoder: JsonDecoder[MyMessage] = DeriveJsonDecoder.gen[MyMessage]
    implicit val encoder: JsonEncoder[MyMessage] = DeriveJsonEncoder.gen[MyMessage]

   implicit val serde =  Serde.string.contramap[T](_.toJson)
}
```

accidentally, we created a message with a null in the list 
```
val myMessage = MyMessage(List(null, "hello"))
``` 

the code `_.toJson` ends up throwing an exception since it is supposed to be a string and it contains a null.

The problem is that the library does not surface this error - it is modeled as an RIO[] but this is actually a defect.

the problem is in the `Serde.string.contramap`
```
 def serialize(topic: String, headers: Headers, value: T): RIO[R, Array[Byte]]

  /**
   * Create a serializer for a type U based on the serializer for type T and a mapping function
   */
  def contramap[U](f: U => T): Serializer[R, U] =
    Serializer((topic, headers, u) => serialize(topic, headers, f(u)))
```

it invokes the `f(u)` without wrapping in the zio - this causes an exception to be thrown that is not caught.

one naive solution is wrap it in zio.attempt (which the library does later in the code) - but obviously fails to prevent the defect from happening here

the problem is in the `Serde.string.contramap`
```
 def serialize(topic: String, headers: Headers, value: T): RIO[R, Array[Byte]]

  /**
   * Create a serializer for a type U based on the serializer for type T and a mapping function
   */
  def contramap[U](f: U => T): Serializer[R, U] =
    Serializer((topic, headers, u) =>  ZIO.attempt(f(u)).flatMap(serialize(topic, headers, _))
```

**Comment by erikvanoosten** [comment]
Hello @lemony312. I have never liked Kafka's serialization support, precisely because of these kinds of reasons. In general I recommend using `Array[byte]` consumers/producers and do the (de)serialization in your own code.

I will look at your PR though.

**Comment by svroonland** [comment]
Just to clarify: did you get a 'died zio' (defect) somewhere or did zio-kafka silently ignore this error somehow?
