### ISSUE TITLE
Cover all features of Kafka Streams

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio-kafka#15]
This should be the first goal here, I believe.

Since I work with Kafka Streams quite frequently, let me brain-dump what we will need to achieve parity:

- [x] Stream source that wraps Kafka consumers (needs to support consumer groups and hence partition assignments but that should be dealt with in the consumer code itself already)
- [ ] Stream sink that wraps Kafka producers
- [x] Stream sources need to properly send heartbeats to not be kicked out of consumer groups (while very busy and while not receiving messages for > heartbeat timeout)
- [ ] Ability to fork and merge streams
- [ ] Kafka "exactly-once" support
- [ ] Ability to provide custom `Serde` instances
- [ ] An abstraction over Kafka topics similar to a `KTable` (which essentially turns a topic into a "table" by treating the topic as a changelog)
- [ ] Exceptions, errors etc. may never destroy the stream source, something equivalent to `DeserializationExceptionHandler` should instead handle these messages

A lot of this can be/is handled by ZIO(-Streams) automatically. 
Some of it is already implemented here, I am just trying to piece together what is still missing.

**Comment by thiloplanz** [comment]
This is a duplicate (or a follow-up, if you consider the `KTable` stuff -- maybe that should be a separate ticket ) of #8 

And yes, being able to use Kafka via ZIO Streams without having to learn Kafka Streams would be awesome.

**Comment by svroonland** [comment]
Are we talking about [Kafka Streams](https://kafka.apache.org/documentation/streams/) or [Alpakka Kafka](https://doc.akka.io/docs/alpakka-kafka/current/home.html)? 

The former does a lot more than the latter, also offering stuff like sliding/tumbling windows, durably stored locally and on the Kafka server.

**Comment by iravid** [comment]
I opened separate tickets for the pending items on this ticket, so closing this one out. Thanks for enumerating these @NeQuissimus!
