### ISSUE TITLE
Remove the semaphore guarding AdminClient

### ISSUE THREAD

**Issue by iravid** [zio/zio-kafka#150]
As helpfully reported by @sderosiaux on Discord:
```
KIP-117 says "The AdminClient will provide CompletableFuture-based APIs that closely reflect the requests which the brokers can handle.  The client will be multi-threaded; multiple threads will be able to safely make calls using the same AdminClient object. "
```

This means we can remove the Semaphore guarding the AdminClient against concurrent operations, simplifying the code.

**Comment by aleksandarskrbic** [comment]
@iravid I would like to take this one if no one working on it.

**Comment by iravid** [comment]
@aleksandarskrbic All yours!

**Comment by ragb** [comment]
is there any developments on this? I'm glad to help since I've been using AdminClient quite intensively.

**Comment by iravid** [comment]
Should be fixed now - thanks for the reminder @ragb!
