### ISSUE TITLE
zio-kafka-testkit

### ISSUE THREAD

**Issue by mvillafuertem** [zio/zio-kafka#155]
Hi @iravid , maybe a little module with test utils can be interesting, what do you think? especially embedded kafka or another version with kafka test container.

**Comment by iravid** [comment]
@mvillafuertem Sure. What did you have in mind?

**Comment by mvillafuertem** [comment]
Hi again @iravid, I am not a ZIO expert like you, but first I thought about starting to create another implementation with TestContainer and testing your current test with this implementation, then splitting all this code into another module like ZLayers and add asserts, utils to create topic, groupId, Kafka cluster.

**Comment by saraiva132** [comment]
I have my own test-kit based on the original utils in test. I extended with a couple more things useful for my own usages. Perhaps the answer would be to extend that and eventually when we are happy enough with the result and it is generic enough extract that to its own module?

**Comment by guizmaii** [comment]
@saraiva132 Is it open-source? I'd love to see your work.

**Comment by tewecske** [comment]
Now there is a test utils module. :)
If you need more stuff in it open a ticket, or add to this one maybe.
