### ISSUE TITLE
Injection of key and value serializers can be ambiguous

### ISSUE THREAD

**Issue by LGLO** [zio/zio-kafka#162]
When I have `Producer[R, A, A]` or `Consumer[R, A, A]` but I want to use different serializers for keys and values `ZLayer` will register only value serializer and will use it to serialize keys.

I propose to introduce a class that encapsulates key and value serializers and use with ZLayer.

**Comment by svroonland** [comment]
Note to future self: this now only applies to  `Producer[R, K, V]`. `Consumer`'s `Deserializer`s are currently passed as regular parameters. 

Also causes some issues on Scala 3: #317

**Comment by svroonland** [comment]
This is fixed with #331
