### ISSUE TITLE
Consider adding one stage produce methods

### ISSUE THREAD

**Issue by LGLO** [zio/zio-kafka#164]
`Producer#produce` and `Producer#produceChunk` are well documented about returning two stage `ZIO of Task`, however even README.md example falls into this pit.

I understand both reason for having lower level two-stage API and one-stage API as well.
See this discussion below: https://discordapp.com/channels/629491597070827530/629497941719121960/704617273557647370

Can we think about `def produceWithAck(record: ProducerRecord[K, V]): RIO[R with Blocking, RecordMetadata]` and `def produceChunkWithAck(records: Chunk[ProducerRecord[K, V]]): RIO[R with Blocking, Chunk[RecordMetadata]]`

I'm wondering what would be better than `WithAck`, any ideas?

**Comment by iravid** [comment]
How about produceNow?

**Comment by LGLO** [comment]
I was thinking about `produceNow` but I'm afraid that it would lead to some doubt about `produce`. Both produce "now". Difference is that `produce` is done when message is enqueued internally (blocking part is done) and `produceXXX` is done when ack is received.
`produceAcked`. I'm wondering if `produce` has right name. Maybe it should become `enqueue`?

Coding part of this issue is trivial. Naming part is hard :D

**Comment by iravid** [comment]
So maybe `produceAsync` for the current version and `produce` for the `.flatten` version?

**Comment by LGLO** [comment]
Ok, I'll prepare this today with updated docs.

**Comment by LGLO** [comment]
Time passes so fast :joy:

**Comment by iravid** [comment]
Closed in #165
