### ISSUE TITLE
Add a diagnostics interface for the consumer

### ISSUE THREAD

**Issue by iravid** [zio/zio-kafka#21]
We don’t want to depend on any logging libraries, but we want to output diagnostics if the user chooses to.

The idea is to create a `DiagnosticEvent` ADT, and a `Diagnostics` service which has an `emit: DiagnosticEvent => UIO[Unit]` function.

We will depend on this service in the run loop and emit diagnostics through it. Two implementations will be provided: a no-op implementation and a sliding queue implementation.

**Comment by andreamarcolin** [comment]
@iravid I would love to try to tackle this if you are not already working on it or planning to do so in a few days, otherwise I will just leave it to you :) Maybe this can be a good opportunity to get some familiarity with the project :)

**Comment by andreamarcolin** [comment]
@iravid Can you give some advice on what events are we interested in from the runloop and maybe clarify what you would expect from the sliding queue implementation? I mean, should the user provide a function to handle the events taken out from the queue (e.g. to enable printing to an external logger) or should we directly print to stdout?

**Comment by iravid** [comment]
Interesting events off the top of my head:
- rebalances
- commits
- requests for partitions
- polls - which partitions were requested, which got data and which did not

For the sliding queue diagnostics constructor, we should create a function that returns a sliding queue wrapped in a case class that implements the diagnostics interface. That case class can be used both for `provide` on the consumer and for accessing the sliding queue and consuming it.

**Comment by iravid** [comment]
Resolved by #43
