### ISSUE TITLE
consuming without groupid

### ISSUE THREAD

**Issue by axaluss** [zio/zio-kafka#212]
i'd love to consume messages without group id. 

Zio kafka does not seem to allow for that

**Comment by svroonland** [comment]
Hi @axaluss, could you explain why you want to do that?

**Comment by axaluss** [comment]
There are use cases where you want to control the offset and partition assignment in the client. Then you don't need a group id at all.

**Comment by svroonland** [comment]
From the apache kafka docs:

```
group.id
A unique string that identifies the consumer group this consumer belongs to. This property is required if the consumer uses either the group management functionality by using subscribe(topic) or the Kafka-based offset management strategy.
```

So you should be able to consume without group ID by using manual partition assignment + manual/external offset retrieval:
 `Consumer.subscribe(Subscription.manual("my_topic" -> 1, "my_topic" -> 2))` + `OffsetRetrieval.Manual(getOffsets: Set[TopicPartition] => Task[Map[TopicPartition, Long]])`. See the zio-kafka [readme on this topic](https://github.com/zio/zio-kafka#partition-assignment-and-offset-retrieval).

I haven't tried it, but let me know if you run into errors.
