### ISSUE TITLE
SOE after 20 minutes of running the app

### ISSUE THREAD

**Issue by sken77** [zio/zio-kafka#218]
I have the following simple `zio.App` program

    val topic = kafkaConfig.userAccount.topic
    val registry =
      new CachedSchemaRegistryClient(kafkaConfig.schemaRegistry, 1)
    val params = Map(
      KafkaAvroDeserializerConfig.SPECIFIC_AVRO_READER_CONFIG -> "true",
      "schema.registry.url" -> kafkaConfig.schemaRegistry
    )
    val serde = new KafkaAvroDeserializer(registry, params.asJava)

    val kafkaSettings =
      ConsumerSettings(kafkaConfig.brokers.split(",").toList)
        .withGroupId(kafkaConfig.userAccount.consumerName)
    
    Consumer
      .consumeWith(
        kafkaSettings,
        Subscription.topics(topic),
        Serde.byteArray,
        Deserializer(serde).map(_.asInstanceOf[UserAccountEvent])
      ) {
        case (_, v) =>
          console.putStrLn(s"message received $v")
      }
      .exitCode

It connects, consumes and parses avro messages just fine. but after 15 minutes or so produces the following error:

`[error] java.lang.StackOverflowError
[error] 	at zio.Schedule$.$anonfun$unfold$3(Schedule.scala:1041)
[error] 	at zio.Schedule$$$Lambda$756/0000000051A60020.apply(Unknown Source)
[error] 	at zio.Schedule$.$anonfun$unfold$3(Schedule.scala:1041)
[error] 	at zio.Schedule$$$Lambda$756/0000000051A60020.apply(Unknown Source)
[error] 	at zio.Schedule$.$anonfun$unfold$3(Schedule.scala:1041)
[error] 	at zio.Schedule$$$Lambda$756/0000000051A60020.apply(Unknown Source)
[error] 	at zio.Schedule$.$anonfun$unfold$3(Schedule.scala:1041)
[error] 	at zio.Schedule$$$Lambda$756/0000000051A60020.apply(Unknown Source)
[error] 	at zio.Schedule$.$anonfun$unfold$3(Schedule.scala:1041)
[error] 	at zio.Schedule$$$Lambda$756/0000000051A60020.apply(Unknown Source)
[error] 	at zio.Schedule$.$anonfun$unfold$3(Schedule.scala:1041)
[error] 	at zio.Schedule$$$Lambda$756/0000000051A60020.apply(Unknown Source)
[error] 	at zio.Schedule$.$anonfun$unfold$3(Schedule.scala:1041)
[error] 	at zio.Schedule$$$Lambda$756/0000000051A60020.apply(Unknown Source)
[error] 	at zio.Schedule$.$anonfun$unfold$3(Schedule.scala:1041)`

**Comment by iravid** [comment]
Can you upgrade to ZIO 1.0.1?

**Comment by sken77** [comment]
I can, but im not depending on zio, im just adding the zio-kafka lib. should I also add that one?

**Comment by svroonland** [comment]
@sken77 Yeah, you can add `"dev.zio" %% "zio-streams" % "1.0.1"` to your `libraryDependencies`.

**Comment by sken77** [comment]
that did it, thanks
