### ISSUE TITLE
List available topics on the connected bootstrap server

### ISSUE THREAD

**Issue by shalastra** [zio/zio-kafka#219]
It would a nice feature to allow list available topics from the connected server. Maybe as a part of `Subscription`?

**Comment by svroonland** [comment]
@shalastra  Have you checked out `AdminClient.listTopics`?

**Comment by shalastra** [comment]
No, I was only looking in `Consumer`, there is a `listTopics` method, however, it works for defined group.

**Comment by svroonland** [comment]
Understandibly. Let me know if AdminClient.listTopics works for you so we can close the issue.
