### ISSUE TITLE
Simplify names of option parameters in AdminClient

### ISSUE THREAD

**Issue by svroonland** [zio/zio-kafka#230]
Follow up from #201:
> On the other hand, however, please note that all other functions in this class use the same naming pattern for options (describeConfigsOptions, createPartitionsOptions, deleteTopicsOptions and 2 or 3 others) which seem to map 1:1 to Java client names, so there's the aspect of the naming consistency involved here as well, that perhaps should be considered as well.

**Comment by regispl** [comment]
I can take a look at it as a followup from my PR.

How much are we concerned with backwards compatibility for APIs like this? What's ZIO's approach to that (generally)? 

Should we introduce a new optional parameter and mark the other one as "deprecated" for now with a plan to completely retire it later or is a simple "rename" just fine (with the understanding that clients will get broken, which means that this shouldn't probably be released right now but as a new `major` version at some point in future?)

**Comment by svroonland** [comment]
That would be much welcome of course!

I suppose deprecation is the nice thing to do here, we can just `orElse` the `Option`s.

In general I would say that for `v < 1.0` there's a bit more room for breaking changes, after 1.0 it's generally appreciated that APIs don't have breaking changes. `zio` core has a binary compatibility check for this.

**Comment by regispl** [comment]
Sure, makes perfect sense 👍

**Comment by svroonland** [comment]
Implemented in #231
