### ISSUE TITLE
Build for 2.13

### ISSUE THREAD

**Issue by iravid** [zio/zio-kafka#24]
Kafka and Embedded Kafka aren't built for 2.13, so we'll need to think what to do there. Maybe not run tests on 2.13.

This could be a good reason to running Kafka on a separate JVM.

**Comment by ghostdogpr** [comment]
I recall they’ve done it in master, just waiting for the next release which should happen in October. 
 Source: https://github.com/apache/kafka/pull/6989#issuecomment-508228402

**Comment by iravid** [comment]
Ah cool. Thanks Pierre

**Comment by neko-kai** [comment]
@iravid 
Could we use `docker-compose` for testing?

**Comment by iravid** [comment]
Yeah totally @neko-kai. At the cost of more memory overhead due to 2 additional JVMs running but totally possible.

If 2.13 is coming in October though it might be easier to wait for that.

**Comment by lvitaly** [comment]
@iravid new tentative release date is Nov 30. possibly 2.13 is coming soon.
https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=125307901

Alpakka is already using Kafka 2.4.0-RC1 for there future release.
https://github.com/akka/alpakka-kafka/pull/971

Maybe it would be possible to adopt RC1 too?

**Comment by iravid** [comment]
PRs welcome!

**Comment by iravid** [comment]
We're now building and publishing for 2.13.
