### ISSUE TITLE
Internally handle commit failures when rebalancing

### ISSUE THREAD

**Issue by svroonland** [zio/zio-kafka#242]
Committing when rebalancing will throw a `RebalanceInProgressException`. We should at the least include this in `Offset.commitOrRetry` or just completely handle it internally. If users want to customize commit behavior when rebalancing is going on for some reason, they can still observe the rebalancing diagnostic events. 

Coming from #241

**Comment by Wosin** [comment]
Happy to at least take a crack at this.

**Comment by svroonland** [comment]
Much appreciated @Wosin! 

However, I think I was too quick to create this issue though. This situation should not occur, since commits are not executed when rebalance is in progress. From `Runloop` lines 320:322.

```scala
      newPendingCommits <- if (!stillRebalancing && state.pendingCommits.nonEmpty)
                            doCommit(state.pendingCommits).as(Nil)
                          else ZIO.succeed(state.pendingCommits)
```

**Comment by svroonland** [comment]
Closing this, as explained above I'm pretty sure I falsely considered this to be an issue.
