### ISSUE TITLE
Enable snapshots

### ISSUE THREAD

**Issue by cipriansofronia** [zio/zio-kafka#256]
It would be great if `zio-kafka` would have snapshots, this way we would not have to wait for a new release.

**Comment by svroonland** [comment]
This is now enabled, see for example https://github.com/zio/zio-kafka/runs/1777201776?check_suite_focus=true

**Comment by cipriansofronia** [comment]
That's great! Many thanks @svroonland !!

**Comment by cipriansofronia** [comment]
@svroonland, how about adding a snapshots badge to the README page? This way other users can see that the snapshots are available.

**Comment by svroonland** [comment]
Good idea, will do
