### ISSUE TITLE
Need ability to use consumer being created with OffsetRetrieval.Manual

### ISSUE THREAD

**Issue by jypma** [zio/zio-kafka#282]
I want to start a consumer at externally-provided partition offsets (in this case, derived from a timestamp). To this end, I'm using `OffsetRetrieval.Manual`, which then in turns wants to call `Consumer.offsetsForTimes` to retrieve the individual partition offsets. However, since `OffsetRetrieval.Manual` is a simple `Set[TopicPartition] => Task[Map[TopicPartition, Long]]`, I can't make any Kafka consumer calls inside it. 

This means that right now I have to start (and end) a second consumer, just to retrieve the offsets. Can perhaps `OffsetRetrieve.Manual` be extended to make non-consuming calls like `offsetsForTimes`, `endOffsets`, etc.? We could inject `Has[Consumer]` as allowed dependency of the returned `Task`, or introduce a simpler base type that only has non-consuming methods.

**Comment by aartigao** [comment]
I face the same limitation and I was thinking if adding more stuff to `AdminClient` can solve the issue 🤔

**Comment by aartigao** [comment]
Actually I've been looking at `AdminClient` and I don't see a way to retrieve `offsetsForTimes`. Your initial suggestion seems the way to go 👍🏽

**Comment by svroonland** [comment]
Sounds good. Gave it a whack, but it's a bit of dependency fiddling to get a `Consumer.Service` in the `Runloop`.

**Comment by ithinkicancode** [comment]
https://github.com/zio/zio-kafka/pull/329

**Comment by svroonland** [comment]
@aartigao Unless I'm mistaken, #330 does not support the use case of getting `offsetsForTimes` right? So this issue can remain open?
