### ISSUE TITLE
Add a way to gracefully shutdown an open stream

### ISSUE THREAD

**Issue by iravid** [zio/zio-kafka#29]
Ideally, this would allow to somehow drain the stream until all already-fetched records have been processed and then close.

**Comment by adamgfraser** [comment]
I would like to work on this.

**Comment by iravid** [comment]
Awesome, thanks @adamgfraser! I haven't yet thought through what changes are needed for this feature and how is it going to look.

Have a look at the codebase and let me know if you have any thoughts.

**Comment by adamgfraser** [comment]
@iravid What if in `Consumer#make` we used `ZManaged#withEarlyRelease` on `ConsumerAccess`, `RunLoop.Deps`, and `Runloop` to get their respective `release` actions? Then we could take all of those effects and store them in a new private field in `Consumer`. And we could expose a new method `Consumer#close` that would invoke the respective release actions and return the already fetched records?

**Comment by adamgfraser** [comment]
@iravid Does this approach make sense to you?

**Comment by iravid** [comment]
Hey @adamgfraser, sorry I missed this. I think we need something a bit more involved bere. 

As a user of the library I'd like to stop consumption of new records from outside (because, e.g., we received a SIGTERM) and wait for all the open streams to end, so that all in-flight records have been processed and committed.

To do this as a user I think needs two parts:
- book-keeping in the runloop that keeps track of how many open streams we have and which of them have been sent the Pull.end; so I can get a `UIO[Unit]` that signals that this is done from the consumer
- and I need a UIO that is resolved by something at the end of each open stream that signals it has received the Pull.end. This is needed for streams with asynchronous boundaries in which being sent the Pull.end from upstream does not necessarily mean that the end of the stream has seen the Pull.end.

What do you think?
