### ISSUE TITLE
Setup CI and publishing

### ISSUE THREAD

**Issue by iravid** [zio/zio-kafka#3]
@NeQuissimus do we have a project structure I could use for this? I know my way around CircleCI so you could throw the general instructions at me :-)

**Comment by NeQuissimus** [comment]
See zio/zio-actors#23
I gave you the same ENV.
See https://github.com/NeQuissimus/zio-slf4j/commit/7b415e760b7ac23c1d5bd54b5b8b9aa2e19b86fc for how to make it work.

**Comment by iravid** [comment]
That's great. Thanks!
