### ISSUE TITLE
Add a microsite

### ISSUE THREAD

**Issue by iravid** [zio/zio-kafka#31]

**Comment by hamednourhani** [comment]
Hi @iravid can I start with this one with some guid from you?

**Comment by iravid** [comment]
@hamednourhani Thanks for picking this up! I'd love to offer guidance but I'm not very knowledgeable about infrastructure for microsites. 

Maybe you could look into how it is configured on ZIO? Or perhaps @softinio could offer guidance as well?

**Comment by hamednourhani** [comment]
Ok I will try to do it

**Comment by softinio** [comment]
@hamednourhani it would be great if you can start by creating the content for the microsite first. Create a folder calls `docs` in the project and create a markdown file for each page of the microsite. 

Once you are done with the content I can help you organize it. Look at ZIO `docs` folder for inspiration. 

Maybe split this work into two PRs: 

- Content
- Setting up the microsite using mdoc and Docusaurus (https://scalameta.org/mdoc/docs/docusaurus.html)

Hope this helps get you started. 

Thanks for helping and taking this on.

**Comment by hamednourhani** [comment]
Thanks @softinio for your help. I will start by docs PR at first 👍

**Comment by hamednourhani** [comment]
@iravid just one question . Which pages we need to creat at first with menus?

**Comment by hamednourhani** [comment]
@softinio hi.as I know little about the project . If somebody else can start it better can help or get this issue from me.

**Comment by TimPigden** [comment]
I'm willing to do some work on this, as blogging / building test usage for zio-kafka is my new project (I need it for work). I'm happy to do pages as md in a docs folder but you'll have to put up with my writing style (which some might find a bit ponderous). Also I've been running/developing code in parallel to the blog and I'm not sure where that would go if here (I can keep it in my github and just post snippets). Or we could just link to the blog as a getting started guide. What do you think?

**Comment by iravid** [comment]
@TimPigden Adding a few md files in a docs folder would be a great start. Someone will eventually pick them up and make a microsite out of them :-)

**Comment by TimPigden** [comment]
Hi @iravid I made a start but decided to hold up until my revised test framework PR is approved because all code samples require that and if there are major changes needed I'd hate to have to rewrite that lot
wip in Client Admin pr

**Comment by svroonland** [comment]
Obsolete, docs are published on https://zio.dev/zio-kafka/
