### ISSUE TITLE
Parallelism by partition and record key 

### ISSUE THREAD

**Issue by Dnomyar** [zio/zio-kafka#315]
Hey folks,

I am looking to implement a kafka consumer. My constraint is low latency. To achieve that, I need parallelism by partition **and key**.
I was looking at `ZStream#mapMPartitioned(_.key)` thats allows to have this parallelism while maintaining the ordering.

But, as mentioned in the documentation of  `mapMPartitioned`, messages are not emitted in order. Thus not committed in order. And having the commit offset jumping around not ideal, confusing and will probably end-up consuming messages that are already processed.

Am I missing something? Is there a simple way to implement that or is there an operator missing in `ZStream`? 

Here is an example code to illustrate:
```scala
 ZStream.fromIterable(1 to 50)
      .map(k =>
        CommittableRecord[Int, String](
          new ConsumerRecord[Int, String]("topic", 1, k, k % 5, ""),
          (partitionOffsets: Map[TopicPartition, Long]) =>
            ZIO(Thread.sleep(40)) *> putStrLn(s"Committing $partitionOffsets")
        )
      )
      .mapMPartitioned(_.key)(record =>
        ZIO.sleep((new Random).nextInt(200).millis)
          .as(record.offset)
      )
      .aggregateAsync(Consumer.offsetBatches)
      .mapM(_.commit)
      .runDrain
```
Output sample:
```
Committing Map(topic-1 -> 19)
Committing Map(topic-1 -> 34)
Committing Map(topic-1 -> 22)
Committing Map(topic-1 -> 39)
Committing Map(topic-1 -> 28)
Committing Map(topic-1 -> 30)
Committing Map(topic-1 -> 27)
Committing Map(topic-1 -> 44)
Committing Map(topic-1 -> 49)
Committing Map(topic-1 -> 36)
Committing Map(topic-1 -> 40)
Committing Map(topic-1 -> 41)
Committing Map(topic-1 -> 46)
Committing Map(topic-1 -> 37)
Committing Map(topic-1 -> 45)
Committing Map(topic-1 -> 50)
Committing Map(topic-1 -> 48)
Committing Map(topic-1 -> 47)
```

**Comment by svroonland** [comment]
Hi @Dnomyar

You are right that this jumping around of offsets is not to be desired.

To ensure sequential commit offsets in this situation, you would have to make something like this after the `mapMPartitioned` stage:
* track a list of the offsets you see emitted
* emit the highest offset and clear the list when you have seen a sequence of offsets without gaps

One solution I can think of would consist of a `mapConcatM` with a function that returns an `Option[Offset]` and a `Ref[Chunk[Offset]]`.

In general though, if you want parallel processing of messages but preserve order by key, it's best to have many partitions, the number of which should be 1 or more times the max parallelism you need. 

Hope this helps, feel free to ask more here or perhaps on the ZIO discord where the response is usually somewhat faster.

**Comment by Dnomyar** [comment]
Hi @svroonland,

Thanks for your answer! 

> - track a list of the offsets you see emitted
> - emit the highest offset and clear the list when you have seen a sequence of offsets without gaps

That's kinda the idea I had in mind. I was a bit reluctant to implement that because it brings some more complexity. It does seems like a nice little exercise though.

As you suggested, **increasing the number of partitions seems to be a good alternative**. We ended up doing that.
