### ISSUE TITLE
Add support for exactly-once messaging

### ISSUE THREAD

**Issue by iravid** [zio/zio-kafka#33]
I've never used that feature of Kafka, so if anyone's knowledgeable about this, feel free to chime in and describe what's needed.

**Comment by ragb** [comment]
This is something I may want to use so I'd like at least to take a look.

Kafka Exactly once delivery in kafka is based around transactions in the producer and isolation levels in the consumer, plus some coordination between them so offset committing is part of a transaction.

I'm not sure if one should just provide the base low level operations (beginTransaction, commitTransaction, etc.) and leave coordination and management to the client or a more high level API would be required, such as:

```scala

Producer.withTransaction { transactionalProducer =>
    processRecords(records) *> transactionalProducer.send(...)
}
```

I'd go for the 2nd option but I'm afraid of losing some flexibility.

Relevant documentation is found here: 

https://www.confluent.io/blog/transactions-apache-kafka/
https://www.confluent.io/blog/exactly-once-semantics-are-possible-heres-how-apache-kafka-does-it/

Please tell me me if this is something to proceed on or not.

**Comment by iravid** [comment]
Your help would be greatly appreciated @ragb! I don’t have any particular opinion on how this should look like, currently. I’ll try to form one over the next few days.

**Comment by ragb** [comment]
I've been researching this a bit more and here goes a very high level proposal which I believe might cover all needs and possible use cases:

1. In `zio.producer.Producer.Service` provide wrappers  around the producer transaction API: `initTransactions()`, `beginTransaction()`,  `abortTransaction()`, `commitTransaction()` and `sendOffsetsToTransaction(offsets, consumerGrouopId)`.
2. In a new zio.transactional` (or similar) package create a more high level API with transaction management as `ZManaged` and other goodies based on existing Producer and Consumer APIs. Still not sure how this would look like, but at least provide some easy way of doing a transaction per consumer record pattern.

**Comment by ragb** [comment]
reflecting a bit more (and while coding it:

) not sure if exposing begin / abort / commit transactions to the end user would be correct since one can't guarantee correctness on usage... A different approach could be providing a Managed object containing only the producer methods that make sense in a transaction context (e.g. send, sendOffsetsToTransaction, flush)... then commit the transaction on success and abort on exception / interruption.

**Comment by svroonland** [comment]
Hi @ragb, Using `Managed` for transactions seems like the right tool for the job to me!

**Comment by gurghet** [comment]
I'd like to pick this up and `Managed` seems a good idea among the one I could think about but the thing is that we can only have one transaction at a time. Furthermore I don't think it's possible to interleave a transaction with messages outside of it.
For this reason I'm working on a simplified API like the following
```
for {
 _ <- Producer.produceAtomically(producerRecord1, producerRecord2, ...)
} yield ()
```
Let me know your thoughts.
