### ISSUE TITLE
Is there a compatibility issue with KafkaProducer  having only types Array[Byte] for both key and value?

### ISSUE THREAD

**Issue by allenjhan** [zio/zio-kafka#347]
Hi there,

We are currently planning on using zio-kafka at Capital One and are working with Ziverge to integrate it into our stack.

We have some existing code written with monix-kafka and want to port it over to use zio-kafka. We are worried about a backwards compatibility issue since our existing code uses a KafkaProducer that has a type signature of [String, Array[Byte]]. This is not the mandatory type signature that zio-kafka uses of [Array[Byte], Array[Byte]] for KafkaProducer.

Will the messages saved to Kafka's log have an issue in this case?

**Comment by adamgfraser** [comment]
@allenjhan I don't think there is any issue here as when we produce we also provide a `Serde` that specifies how to serialize and deserialize values of a given type so we can simply use a `Serde.string` to serialize string keys when we produce.

**Comment by allenjhan** [comment]
I tried reading some code in the zio.kafka.Producer to contextualize your response but still wasn't really able to understand the point you are making. I guess we can discuss this tomorrow during the code review for my PR. For now, it's ok I guess to close this issue then.

**Comment by adamgfraser** [comment]
Sounds good. We can definitely go through it tomorrow.
