### ISSUE TITLE
Proper commits during cooperative rebalances

### ISSUE THREAD

**Issue by susliko** [zio/zio-kafka#413]
## Current commit logic
It is [assumed](https://github.com/zio/zio-kafka/blob/68977a1b93f3b249e28b9ecac8cae3dee457c787/src/main/scala/zio/kafka/consumer/internal/Runloop.scala#L61-L62) that a rebalance is started whenever the `onPartitionsRevoked` method is called and is finished whenever the `onPartitionsAssigned` method is called. [Afterwards](https://github.com/zio/zio-kafka/blob/68977a1b93f3b249e28b9ecac8cae3dee457c787/src/main/scala/zio/kafka/consumer/internal/Runloop.scala#L338) the library tries to commit pending messages if there is no ongoing rebalance.

## The problem
Described behaviour is correct for the eager rebalance. However, the assumptions about a rebalance start/end are incorrect for the cooperative rebalance strategy (which is [going](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=177048248) to become a default):
1. `onPartitionsRevoked` is called at the end of the rebalance. From the [docs](https://kafka.apache.org/28/javadoc/org/apache/kafka/clients/consumer/ConsumerRebalanceListener.html#onPartitionsRevoked(java.util.Collection)):
> In eager rebalancing, it will always be called at the start of a rebalance and after the consumer stops fetching data. In **cooperative rebalancing, it will be called at the end** of a rebalance on the set of partitions being revoked iff the set is non-empty
2. `onPartitionsAssigned` is called more than once, since a cooperative rebalance consist of multiple phases

This results in a consumer attempting commits while a rebalance is still in progress, which triggers an unhandled `RebalanceInProgressException`.

## Possible solution
To address the issue we could implement retries whenever this exception bubbles up.

Also, it might be a good idea to override the `onPartitionsLost` method: its invocation usually means that something's going wrong and the cleanup should be started (e.g. offsets commit). The default implementation of this method is equivalent to the `onPartitionsRevoked` call and is considered as a rebalance start

**Comment by svroonland** [comment]
@susliko Thanks for bringing up this issue. I think what you're proposing should be relatively easy to implement.

Also, `onPartitionsLost` was implemented as part of #427 recently and available in v0.17.5.

**Comment by svroonland** [comment]
@susliko Would you be able to describe how to reproduce this situation? Like broker settings and a series of steps

**Comment by susliko** [comment]
@svroonland
Sure!
I'll try to get to it in a few days

**Comment by susliko** [comment]
@svroonland 
Wrote a [test](https://github.com/susliko/zio-kafka/commit/896dd5b75be4f7830af190ac9ba7e7c6949464d7), which reproduces the `RebalanceInProgressTest`

**Comment by svroonland** [comment]
That's great, thanks! 

I found that my proposed fix (#437) doesn't work, I'll need to try something different though.
