### ISSUE TITLE
Handle RetriableCommitFailedException

### ISSUE THREAD

**Issue by svroonland** [zio/zio-kafka#42]
In my experience commits sometimes fail because of some temporary situation, like a network timeout. Kafka will then throw a `RetriableCommitFailedException`. This should not fail the consumer.

We should probably handle this in the callback passed to `commitAsync` in the `RunLoop`

**Comment by iravid** [comment]
Failed commits will not fail the runloop; the failure will be passed back to the caller of `OffsetBatch#commit`. The alternative is to bake in a `Schedule` that will be used for retrying commits in the runloop, but I feel that is best delegated to the caller.

What do you think?

**Comment by svroonland** [comment]
That makes sense, to leave it to the caller. Might be good to add it as a recommendation in the docs somewhere, and it would be nice to have that behavior in `consumeWith`.

**Comment by iravid** [comment]
👍

**Comment by svroonland** [comment]
This was implemented in #81. Shall we close it @iravid ?

**Comment by svroonland** [comment]
I'll take that as a yes :)
