### ISSUE TITLE
Throughput issue

### ISSUE THREAD

**Issue by svroonland** [zio/zio-kafka#428]
Reported by `krille` on the [zio-kafka Discord](https://discordapp.com/channels/629491597070827530/629497941719121960/940169418615431182):

> Hi! Experiencing some weirds issues with zio-kafka message throughput and latency. 
>
>Given the follow settings: 
>- `pollTimeout=20000ms`
>- `fetch.max.wait.ms=10000ms` 
>- `fetch.min.bytes=1` 
>- `max.poll.records=10`
>
>Using only the low level confluent java consumer api everything works as expected. 
>Let's say we have a running consumer on a topic - and no messages in lag. 
>Then pushing 100 records into this topic at once results in: 
>  1. the consumer immediately returns from poll with 10 records 
>  2. processes the records and commits 
>  3. calls poll 
>  4. immediately returns with 10 new records.... 
>and this goes on until there is no more lag. 
>
>With zio-kafka the result is totally different. 
>It always seems to call poll for 20 seconds (never returning immediately even if `fetch.max.wait.ms`, `fetch.min.bytes`, `max.poll.records` has been satisfied). 
>I'm struggling to find the cause for this. 
>The code is based on examples from zio-kafka documentation and zio-kafka test code. 
>
>Can provide more detailed code examples if needed. 
>Is there some important considerations to take between setting `pollTimeout` and `pollInterval` (in zio-kafka)? Has anyone ever experienced any issues like this?
>
> More investigation reveals that this weird behaviour is a result of committing the offsets. 
>`offsets.commitOrRetry(Schedule.spaced(100.milliseconds) && Schedule.recurs(10))` seems to blocks for the same amount of time as the pollTimeout.

```scala
ConsumerSettings(
  List(localhost:9092),
  HashMap(
    heartbeat.interval.ms -> 3000, 
    security.protocol -> PLAINTEXT, 
    group.id -> test_blurp_1, 
    request.timeout.ms -> 30000, 
    session.timeout.ms -> 10000, 
    fetch.max.wait.ms -> 10000, 
    fetch.min.bytes -> 1, 
    max.poll.records -> 10, 
    max.poll.interval.ms -> 300000
  ),
PT30S,PT0.1S,PT10S,2,Auto(Latest),RebalanceListener(zio.kafka.consumer.RebalanceListener$$$Lambda$1583/0x0000000800b52840@6c365988,zio.kafka.consumer.RebalanceListener$$$Lambda$1584/0x0000000800b53840@3a0dc0d9))
```

**Comment by svroonland** [comment]
The issue disappears when commenting this line: https://github.com/zio/zio-kafka/pull/429/files#diff-4bb68de9081869e01fdb038a48581bb121471b3de1ddad2cf0e834e4e3e356fdR250
`c.pause(toPause.java)`, so this looks like it has something to with pausing of partitions.

**Comment by svroonland** [comment]
@iravid What do you make of this? Could this be some sort of race condition between the processing of a chunk of records and a new 'pull' for records on that partition, causing one or more partitions to be paused?

**Comment by svroonland** [comment]
After experimenting a bit, some notes about current polling behavior and the effect of various settings.

* When a consumer is started, several `poll` calls are made to the broker as part of joining the consumer group, to gather topic metadata and join the consumer group. These calls are performed according to the configured `pollInterval`. A high `pollInterval` value will therefore result in a long startup time before any records are processed.
* Poll calls and commit calls (for all currently queued commits) are executed in turns. This means that if you have a high value for `pollTimeout` or `fetch.max.wait.ms`, the commits will have to wait while a poll is in progress, which may be up to the timeout period when there are no new messages on the topic. 
  * It also looks the [optimization to immediately poll again](https://github.com/zio/zio-kafka/blob/v0.17.4/src/main/scala/zio/kafka/consumer/internal/Runloop.scala#L393) when there are still pending requests in combination with the partition pausing issue will actually result in commits having to wait close to 2x`pollTimeout`s, before they are [dequeued](https://github.com/zio/zio-kafka/blob/v0.17.4/src/main/scala/zio/kafka/consumer/internal/Runloop.scala#L81). 
* Currently I would recommend to keep `pollTimeout` <= `pollInterval` and keep the `pollInterval` relatively small (< 1s) to ensure fast startup and low commit latencies.

 I would like to see if we can optimize some of this before we add this behavior to the documentation.

**Comment by iravid** [comment]
Sorry, I’ve not had time yet to read this thread. But I have some ideas on how to improve the handling of commits - @svroonland will try to catch up with you on Discord this week

**Comment by guizmaii** [comment]
@svroonland I wonder if the issue we have is not the use of `Schedule.spaced`, instead of `Schedule.fixed`

I tried to compare the two in this unit test: https://github.com/zio/zio-kafka/pull/661/files#diff-da9b0f09a6f77f19a83bd83ab57a89fe658f8ff4e8e82217f2fb0e79c68b42b2R15-R90

It seems that `Schedule.spaced` is "stacking the wasted/lost time" while `Schedule.fixed` is "recovering the wasted/lost time".
I'm not sure my analogies are very good but the doc of `Schedule.fixed` is IMO explaining this quite well:

<img width="877" alt="image" src="https://user-images.githubusercontent.com/1193670/221411056-04f2ab3b-30b8-4131-b1af-93210861a9a3.png">

`Schedule.fixed` is doing this:
```scala
* |-----interval-----|-----interval-----|-----interval-----|
* |---------action--------||action|-----|action|-----------|
```

while, I think that, `Schedule.spaced` is doing this:
```scala
* |-----interval-----|-----interval-----|-----interval-----|
* |---------action--------||---------action--------||---------action--------|
```

**Comment by erikvanoosten** [comment]
Prior to version 2.2 polling happened on a schedule. Since version 2.2 polling happens continuously. So the wait time between polls is no longer there. If you can not upgrade yet, lower the `pollTimeout` setting. The default value is 50ms which is good enough for most situations.

BTW version 2.3.0 contains more performance improvements and approaches throughput of the Java client.
