### ISSUE TITLE
100% cpu usage when using Consumer.consumeWith

### ISSUE THREAD

**Issue by GiGurra** [zio/zio-kafka#447]
After discussion on the zio slack with `svroonland#7332` we concluded to open an issue here.
The original question/report follows below:

Hi, we are experiencing some very high cpu usage numbers (> 1 cpu core for every started consumer) for what we believe are some basic use cases of zio-kafka. 

The issues started when we tried upgrading to zio2 compatible M1 and M2 releases (same issue in both).
In short, we experience the issue in zio2RC2+zioKafkaM1, RC3+M2, regardless of using scala2 or scala 3. 

Our minimum reproducing test code looks like this:
```

object Main extends ZIOAppDefault {

  private val kafkaConfig = ConsumerSettings(List("localhost:9092"))
    .withGroupId("any-group")

  private val topic        = "any-topic"
  private val subscription = Subscription.topics(topic)

  def run =
    (for {
      _ <- ZIO.logInfo("Starting program...")
      _ <- Consumer.consumeWith(kafkaConfig, subscription, Serde.string, Serde.string)((key, value) => ZIO.log(value))
    } yield ExitCode.success)
      .catchAllCause(err =>
        for {
          _ <- ZIO.logError(s"Failed to run program with err: [$err]")
          a <- ZIO.succeed(ExitCode.failure)
        } yield a
      )

}

```

regardless of schedules or idle-ness or availability (kafka on or off) the cpu usage stays very very high. This wasnt the case in earlier versions...We also tried a few different poll and timeout numbers, but that unfortunately had no affect either

![image](https://user-images.githubusercontent.com/1761299/160599024-4be17eaa-d29d-4594-ac80-ccb360c0e131.png)

------------------------------------------------------

Cause and workaround:

It seems that ZIO2 implementaion of ZStream, its scheduler and other parts have changed quite a bit. The `.aggregateAsync` method seems to have new semantics (or it might be a bug in the `ZStream.aggregate...` methods), which might be the cause of all this.

Regardless, the following change reduces the cpu usage, but I dont know if it breaks other functionality in the process (I am new to zio and zio-kafka)

Changing the following line in the `override def consumeWith[R: Tag, R1: Tag, K, V](` method from

```
...
.aggregateAsync(offsetBatches)
```

into 
```
.aggregateAsyncWithin(offsetBatches, Schedule.fixed(settings.pollInterval))
```

result:
![image](https://user-images.githubusercontent.com/1761299/160601157-831bbee6-044f-4537-874c-e78b3da72dc6.png)

fixes the problem, but again - I dont really have enough experience with zio or zstreams or zio-kafka to understand what semantic implications this change has. Maybe ZStream itself is broken at the moment and we are just adding workarounds by doing the above and limiting other throughput?

**Comment by GiGurra** [comment]
Using the `settings.pollInterval` here is probably wrong, but you can probably decide on what is right. I ended up changing the parameter to aggregateAsyncWithin to hard coded 10 seconds instead. I have no idea what kind of side effects this might have ;)

**Comment by googley42** [comment]
I am not a zio-kafka user but I [reported this bug with `agregateAsync` in RC2](https://github.com/zio/zio/issues/6395) and may be related to your problem - it got fixed I think in for RC3

**Comment by GiGurra** [comment]
> I am not a zio-kafka user but I [reported this bug with `agregateAsync` in RC2](https://github.com/zio/zio/issues/6395) and may be related to your problem - it got fixed I think in RC3

The problem in zio-kafka is there also in RC3, so unfortunately that doesnt fix it

**Comment by adamgfraser** [comment]
I recently did a fix to the implementation of `aggregateAsyncWithin` so may be good to test on the next ZIO 2 release candidate when available.

**Comment by GiGurra** [comment]
> I recently did a fix to the implementation of `aggregateAsyncWithin` so may be good to test on the next ZIO 2 release candidate when available.

Unfortunately the problem remains in RC5 (zio-kafka 2.0.0-M3)

**Comment by adamgfraser** [comment]
This was subsequent to `RC5`.

**Comment by GiGurra** [comment]
> 

Is there a snapshot repo & release I can depend on to see if your newer version works?

**Comment by GiGurra** [comment]
> This was subsequent to `RC5`.

Is there a snapshot repo & release I can depend on to see if your newer version works?

**Comment by adamgfraser** [comment]
The latest ZIO snapshot.

**Comment by johan-kjolhede-rocker** [comment]
> The latest ZIO snapshot.

How do I depend on that? Is there an instruction somewhere?

**Comment by johan-kjolhede-rocker** [comment]
@adamgfraser unfortunately it doesnt seem like zio-kafka has any release compatible with later zio2 (e.g. rc6), or I am missing something? I end up with class/method missing errors.

**Comment by GiGurra** [comment]
Oh, heh, sorry. I realize now that I logged in as a different user. The one above :S . sorry about that @adamgfraser , but yeah, that above was also from me

**Comment by svroonland** [comment]
@GiGurra There is #464 which is work in progress

**Comment by svroonland** [comment]
@GiGurra Are you still experiencing this issue with the latest ZIO-2 compatible zio-kafka release?

**Comment by GiGurra** [comment]
I believe it is no longer an issue. We have removed our workaround and still have normal cpu usage
