### ISSUE TITLE
Access to underlying kafka Consumer/Producer

### ISSUE THREAD

**Issue by newffy** [zio/zio-kafka#452]
Sometimes it would be great to have ability to configure underlying consumer/producer directly.
Right now it can be configured via settings, but sometimes you need access to original object.
Probably it can be done in the same way as it's implemented in `alpakka kafka` project, via smth like 
`ProducerSettings.withProducerFactory` or `ProducerSettings.withProducer`

**Comment by guizmaii** [comment]
@newffy Can you please give us a concrete example where you'd need this?
I'm not sure to see the need
