### ISSUE TITLE
Enable user registration of a rebalance listener

### ISSUE THREAD

**Issue by rudolfduplessis** [zio/zio-kafka#46]
KafkaConsumer takes a rebalance listener on topic subscription. I think it's wise to follow the usage semantics in this case. I'm thinking something in the line of:

def myRebalanceListener(rebalance: Rebalance): ZIO[Any, Nothing, Unit]
consumer.subscribe(Subscription.topics("my-input-topic"), myRebalanceListener)

subscribe method could be overloaded or given a ZIO.succeed as default for the none case.
This will however mean that the listener creation in Runloop can't occur on Deps.make anymore, unless we want to pass the user's listener via Consumer.make which I don't find that appealing. Either case the goal as I see it is getting the following line in Runloop under "new ConsumerRebalanceListener" (lines 80 and 88 at time of writing) to resemble e.g.:

```
for {
_ <- rebalancingRef.set(true)
rebalanceEvent = Rebalance.Revoked(partitions.asScala.toSet)
_ <- rebalances.offer(rebalanceEvent ).fork //or diagnostics emit when that's merged
_ <- userRebalanceListener(rebalanceEvent)
} yield ()
```
On a rebalance, your poll call is blocked until all rebalance listeners have completed. This could be longer than pollFrequency and I'm not sure if this will be an issue, some insight required here.

**Comment by svroonland** [comment]
I think this functionality is covered by `Diagnostics`, which was merged in #43  just before #51 was opened. Would you agree, @rudolfduplessis ?

**Comment by rudolfduplessis** [comment]
I see yes. Judging by my first comment ("//or diagnostics emit when that's merged") I think I didn't exactly have the whole picture at that time. I'm sure if there's nothing else we close this and I'll remove the pull request. Sorry haven't had time to pay attention to this for a while.

**Comment by svroonland** [comment]
Ah, I didn't see the diagnostics emit comment. 

No worries.

Alright, will close this issue.
