### ISSUE TITLE
Fix flaky restartStreamsOnRebalancing test

### ISSUE THREAD

**Issue by vigoo** [zio/zio-kafka#479]

**Comment by mhodovaniuk** [comment]
Hi @vigoo 
By any chance do you have an idea what is wrong with it? I would like to fix it. 
E.g. it failed [here](https://github.com/zio/zio-kafka/runs/7175551877?check_suite_focus=true#step:5:403) . And I am not sure how it happens that we consumed 30 items from 0 partition.

**Comment by vigoo** [comment]
No I didn’t have a chance to look into it yet

**Comment by vigoo** [comment]
I think I fixed it in #498

**Comment by erikvanoosten** [comment]
The test is no longer flaky.
