### ISSUE TITLE
Why are all the low-level (Java) Kafka AdminClient calls wrapped in `effectBlocking`?

### ISSUE THREAD

**Issue by guizmaii** [zio/zio-kafka#492]
AFAIK, and seeing that the Kafka AdminClient is using Java Futures (`KafkaFuture` implementing `java.util.concurrent.Future` and being based on `CompletionStage` since Kafka 3.1 or 3.2), why are all the calls made with this client wrapped in a `effectBlocking`?

Random example took from the code of zio-kafka:
```scala
    /**
     * List offset for the specified partitions.
     */
    override def listOffsets(
      topicPartitionOffsets: Map[TopicPartition, OffsetSpec],
      options: Option[ListOffsetsOptions] = None
    ): Task[Map[TopicPartition, ListOffsetsResultInfo]] = {
      val asJava = topicPartitionOffsets.bimap(_.asJava, _.asJava).asJava
      fromKafkaFuture {
        blocking.effectBlocking(
          options
            .fold(adminClient.listOffsets(asJava))(opts => adminClient.listOffsets(asJava, opts.asJava))
            .all()
        )
      }
    }.map(_.asScala.toMap.bimap(TopicPartition(_), ListOffsetsResultInfo(_)))
```

**Comment by guizmaii** [comment]
Because of this `synchronized`:
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/1193670/183129899-98ea94b6-e4dc-4717-b50d-7224cf475c53.png">
??

**Comment by svroonland** [comment]
@guizmaii What shall we do with this one year old issue?

**Comment by guizmaii** [comment]
@svroonland I'm still waiting for an answer/to understand why we need this and if we should keep these usages of blocking
I'd prefer to leave it open if that's ok for you

**Comment by svroonland** [comment]
I suppose it was originally written that way as a precaution and probably after some actual experience of blocking in some circumstances.

**Comment by svroonland** [comment]
With java code you never know whether it's blocking or not. ZIO 2's automatic blocking detection (and shifting to a blocking thread) and the chance of actual blocking in the AdminClient being pretty low given that it's using Java future, I think we can safely remove the explicit blocking here.
