### ISSUE TITLE
stream setup fails without generating error messages

### ISSUE THREAD

**Issue by xelax** [zio/zio-kafka#501]
The following program, which tries to open a non-existent kafka server, 
fails without producing an error message:
```
package zstream
import org.apache.kafka.clients.consumer.ConsumerConfig
import zio.kafka.consumer.*
import zio.kafka.serde.Serde
import zio.stream.*
import zio._

import java.nio.file.Paths
import java.util.concurrent.TimeUnit

object Minimal extends ZIOAppDefault {
  val topic   = "none"
  val servers = "badserver"

  override def run = {
    val expectedCount = 10
    val settings      = ConsumerSettings(List(servers))
      .withGroupId(s"zio-kafka-${scala.util.Random.nextInt()}")
      .withProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest")
      .withPollInterval(150.millis)
      .withPollTimeout(150.millis)

    Consumer
      .subscribeAnd(Subscription.topics(topic))
      .plainStream(Serde.byteArray, Serde.byteArray)
      .tap(cr => Console.printLine(s"msg size ${cr.value.size / 1024} Kb"))
      .take(expectedCount.toLong)
      .runDrain
      .provideLayer(ZLayer.scoped(Consumer.make(settings)))
      .exitCode
  }
}
```

when run it just writes: 
```

Process finished with exit code 0
```

this is using dependency
```
libraryDependencies += "dev.zio" %% "zio-kafka"              % "2.0.0"
```

**Comment by adamgfraser** [comment]
@xelax You need to delete `exitCode` there. The conversion of the result of running your application to an `ExitCode` is already handled by `ZIOAppDefault`. By calling this operator yourself you are converting the success or failure to a single exit code and throwing away all additional information about the error that occurred.

**Comment by xelax** [comment]
I see. Thanks: you are right. when I remove i can finally see the errors. I was taking https://github.com/zio/zio-kafka/blob/master/src/test/scala/zio/kafka/Benchmarks.scala#L76 as an example to write my own app because I did not find a whole worked out example in the README, and I did not understand the implications of  `exitcode`

**Comment by xelax** [comment]
I think it would help to have a whole example app with the main method and all: I am starting with zio-kafka directly instead of first learning zio, so having a good working example is critical

**Comment by xelax** [comment]
Thank you so very much for being so helpful and responsive!

**Comment by adamgfraser** [comment]
@xelax No worries! I just submitted a PR to update those benchmarks to not use `exitCode`.

**Comment by adamgfraser** [comment]
And totally agree with you about the example. Can you look at the one here and see if it is what you are looking for?

**Comment by xelax** [comment]
where?

**Comment by adamgfraser** [comment]
Sorry, forgot to include the link.

https://zio.dev/resources/ecosystem/officials/zio-kafka

**Comment by xelax** [comment]
it is good, but I'd like a simpler example as well with just a consumer: i think that would be the more typical beginner example , since normally you have some topic you would like to read from. Also an example of how you wrap an avro decoder in a Serde:

**Comment by adamgfraser** [comment]
Good feedback.

@khajavi See above.

**Comment by khajavi** [comment]
@xelax 
Thank you for the feedback. Will try to add a simpler one.
