### ISSUE TITLE
Wild console prints since v0.17.6

### ISSUE THREAD

**Issue by aartigao** [zio/zio-kafka#503]
The following `ZIO.debug` statements were added with last release:

https://github.com/zio/zio-kafka/blob/352472211f36b1d5e4656a73a052b203a3a9a6ed/src/main/scala/zio/kafka/consumer/internal/Runloop.scala#L60

https://github.com/zio/zio-kafka/blob/352472211f36b1d5e4656a73a052b203a3a9a6ed/src/main/scala/zio/kafka/consumer/internal/Runloop.scala#L73

https://github.com/zio/zio-kafka/blob/352472211f36b1d5e4656a73a052b203a3a9a6ed/src/main/scala/zio/kafka/consumer/internal/Runloop.scala#L78

https://github.com/zio/zio-kafka/blob/352472211f36b1d5e4656a73a052b203a3a9a6ed/src/main/scala/zio/kafka/consumer/internal/Runloop.scala#L85

I guess they were there for debugging purposes and shouldn't have reached release code. In any case, I want to ask here first ⚠️

**Comment by vigoo** [comment]
Yes that was me, sorry ;) Will do a new release today

**Comment by vigoo** [comment]
https://github.com/zio/zio-kafka/releases/tag/v0.17.7
