### ISSUE TITLE
Many instances lead to consumer poll timeout has expired

### ISSUE THREAD

**Issue by erikvanoosten** [zio/zio-kafka#510]
When we start a huge number of zio-kafka instances, some of these instances do not get any partitions assigned. These instances quite quickly log the following message:

```
consumer poll timeout has expired. This means the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time processing messages. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.
```

We are not sure these 2 facts are related.

**Comment by svroonland** [comment]
Are you starting these instances within the same JVM? Each zio-kafka Consumer instance is backed by an Apache Kafka instance which comes with a thread pool. A large number may lead to issues. If the instances are running on separate JVMs, it's possible that the broker is overloaded and requests time out.

#517 may be of interest to you.
