### ISSUE TITLE
Add basic integration tests

### ISSUE THREAD

**Issue by iravid** [zio/zio-kafka#6]
The tests should exercise the consumer and producer APIs against a local Kafka instance. 

Two options to provide the Kafka instance required for the tests:
- launch Zookeeper and Kafka containers as secondary containers before the test commands in the CircleCI config (see https://circleci.com/docs/2.0/configuration-reference/#docker)
- use https://github.com/embeddedkafka/embedded-kafka to run Kafka programatically from the test suites

**Comment by NeQuissimus** [comment]
Could also use https://github.com/testcontainers/testcontainers-Java but I prefer embedded-Kafka. (although I am biased, of course)

**Comment by pierangeloc** [comment]
I have some experience with embedded-kafka so I would go for that
Is there a standard library for testing that should be used in ZIO projects (testz or specs2)? If not, what should we use?

**Comment by iravid** [comment]
No strong opinions here, I’m fine with either. Whatever you’re comfortable with.

**Comment by pierangeloc** [comment]
👍 I can start working on this

**Comment by iravid** [comment]
Resolved by #10
