### ISSUE TITLE
[Feature Request] provide access to the underlying kafka consumer

### ISSUE THREAD

**Issue by tnielens** [zio/zio-kafka#694]
At my workplace we have lots of functionality working on the java consumer for concerns like healthcheck, consumer lag monitoring etc. 
Could the zio-kafka consumer provide access to the underlying consumer? That would allow us to reuse the functionality without rewriting it against the zio-kafka Consumer methods.

**Comment by guizmaii** [comment]
I need to finish this PR which allows you to have access to the underlying Java consumer. We already this approach for a while where I work

**Comment by svroonland** [comment]
Now available in https://github.com/zio/zio-kafka/releases/tag/v2.4.2
