### ISSUE TITLE
People using the Consumer to do something else than consume will experience a `RunloopTimeout`

### ISSUE THREAD

**Issue by guizmaii** [zio/zio-kafka#856]
As discussed with @erikvanoosten on discord, because we start the runloop when we instantiate the Consumer, if a user is only using the utility methods provided by the Consumer (ie. `::beginningOffsets`, `::endOffsets`, etc.), after some time, the Consumer will throw a `RunloopTimeout`.

This problem is preventing people only using these utility methods to upgrade to `v2.3+`

See the discussion starting here: https://discord.com/channels/629491597070827530/629497941719121960/1108325068284633158

**Comment by erikvanoosten** [comment]
While a serious solution is pending, you can already upgrade to v2.3 by configuring a very high runloop-timeout (e.g. a timeout of 20 years). The only use case where this does not work is when the consumer is actually used for consuming as well.
