### ISSUE TITLE
Update zio-quickstart-kafka example

### ISSUE THREAD

**Issue by guizmaii** [zio/zio-kafka#898]
Some people on Discord were mentioning that the quick start example was out-of-date.
That'd be nice if someone could update it

See https://github.com/zio/zio-quickstarts/tree/master/zio-quickstart-kafka

**Comment by GrigoriiBerezin** [comment]
Hey, I'm kind of a newbie in open source, may I take this issue?

**Comment by guizmaii** [comment]
> Hey, I'm kind of a newbie in open source, may I take this issue?

Please do :)

**Comment by GrigoriiBerezin** [comment]
Sorry for long wait, done
https://github.com/zio/zio-quickstarts/pull/46
