### ISSUE TITLE
Handle messages that the Serde cannot deserialize

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio-kafka#9]
Kafka Streams has a global "Exception handler" for messages that could not be deserialized or otherwise triggered exceptions.
We should somehow have something like that, otherwise a single misformatted message will rip down the app too easily (or one would have to always be aware of this happening).

In order to reduce boilerplate on the implementer's side, we should find some nice way to handle "bad messages".
I would limit handling of issues to that. All other exceptions should indeed be handled by the stream's implementer.

**Comment by iravid** [comment]
@NeQuissimus when using the `LogAndContinueExceptionHandler`, does Kafka Streams commit the offset properly even though the message was dropped?

**Comment by NeQuissimus** [comment]
Yes, definitely. At work, I actually created a custom handler that puts invalid messages on a separate topic.

**Comment by iravid** [comment]
Closing in favor of #30
