### ISSUE TITLE
Replace runloop timout with per stream halting detection

### ISSUE THREAD

**Issue by erikvanoosten** [zio/zio-kafka#902]
Kafka's process to detect halted consumers is a kind of crude. Because it is based on polls, it works per consumer. We can make it more fine grained. E.g. by doing the detection per subscription. When one of the streams associated with that subscription halts, we can unsubscribe just that subscription.

For the Kafka client 'halting' means poll is not called for more than `max.poll.interval.ms`. Translated to zio-kafka 'halting' means that a stream does not require more data for more then `max.poll.interval.ms`.

A halted stream should be interrupted so that it can fail properly.

As discussed on [Discord](https://discord.com/channels/629491597070827530/629497941719121960/1114868628156858400).

Replaces #686.

**Comment by guizmaii** [comment]
🔥
