### ISSUE TITLE
Add module pattern and service for AdminClient

### ISSUE THREAD

**Issue by TimPigden** [zio/zio-kafka#93]
I want to pass adminclient around as an environment service and since it's a fairly heavy-weight object it seems the sensible way to do it.
I can make the additions in the  AdminClient.scala file without causing any problems I think

**Comment by iravid** [comment]
We should do that for the Consumer and Producer as well. If possible, in a way that is not intrusive - that is, non-module usage is still unaffected.

**Comment by TimPigden** [comment]
I thought of that, but do they get passed around in the same way? I've only ever declared and used them in a single spot (though I've only just started doing "real" kafka stuff). So I don't think I'm qualified to figure what it should look like.
For the AdminClient I was going to create a KafkaAdmin service so there was no name clash and use the current AdminClient case class as an implementation of the KafkaAdmin.Service

**Comment by TimPigden** [comment]
done and merged
