### ISSUE TITLE
Duplicate events appear when using single Consumer with multiple subscriptions

### ISSUE THREAD

**Issue by myazinn** [zio/zio-kafka#988]
Here's a test for [SubscriptionsSpec](https://github.com/zio/zio-kafka/blob/master/zio-kafka-test/src/test/scala/zio/kafka/consumer/SubscriptionsSpec.scala).
In this test, I subscribe to `topic1` and `topic2` using the same `Consumer` but within different streams, and then publish one message to each topic. However, for some reason I get the same event twice from `topic1`.

```scala
    test("consumes from two topic subscriptions without duplicates") {
      def plainStream(topic: String) =
        Consumer.plainStream(Subscription.topics(topic), Serde.string, Serde.string)

      // .delay imitates long processing
      def readCount(topic: String)(counter: Ref[Int]) =
        plainStream(topic).runForeach(_.offset.commit.delay(500.millis) *> counter.update(_ + 1))

      def readOne(topic: String) =
        plainStream(topic).take(1).runDrain

      def writeSingleTo(topics: String*) =
        ZIO.foreachParDiscard(topics)(topic => produceOne(topic, s"key-$topic", s"value-$topic"))

      for {
        topic1 <- randomTopic
        topic2 <- randomTopic
        client <- randomClient
        group  <- randomGroup

        c = consumer(client, Some(group))

        counter <- Ref.make[Int](0)
        _ <- (readCount(topic1)(counter).fork *> readOne(topic2).zipPar(writeSingleTo(topic1, topic2)))
               .zipPar(ZIO.sleep(3.seconds)) // give consumer some time to poll events
               .provideSome[Producer with Kafka](c)

        count <- counter.get
      } yield assertTrue(count == 1)
    }
```
This test fails because `count` is equal to 2.
I couldn't find the root cause yet, but it appears that when we stop reading from `topic2` there's some internal restart, which causes events to be read from Kafka again event though there're some messages pending in memory. Because of it, we might consume the same message several times which is definitely wrong in this case.

**Comment by erikvanoosten** [comment]
What clock is this test using?

**Comment by erikvanoosten** [comment]
Do I read it correctly that this test reads from topic2 and then produces that record to topic1 _and_ topic2. If I read that right, this creates a duplicate on topic2.

I am missing commits on topic2. So consuming from topic2 again might cause duplicates when using the same consumergroup. This might happen depending on the implementation of `randomGroup`.

**Comment by guizmaii** [comment]
I'm wondering if it's not due to my change in #857 about the `Hub` 🤔

**Comment by myazinn** [comment]
@erikvanoosten this test uses real clock.
The logic is a bit different: we subscribe to topics `topic1` and `topic2`, and produce exactly one message to each of them. You are right, we don't commit message read from `topic2`, but it shouldn't matter since we count messages read from `topic1`. `topic1` is the one we care about, it has exactly one message, but in this test it is processed twice for some reason.

**Comment by myazinn** [comment]
@guizmaii here're messages
```
Assertion failed:
  ✗ 2 was not equal to 1
  count.size == 1
  .size = 2
  count = Chunk(CommittableRecord(
    record = ConsumerRecord(topic = subscriptionsspec-topic-5cdcfac7-72be-434e-9f8a-c6d9b0adcddd, partition = 0, leaderEpoch = 0, offset = 0, CreateTime = 1689838595394, serialized key size = 64, serialized value size = 66, headers = RecordHeaders(headers = [], isReadOnly = false), key = key-subscriptionsspec-topic-5cdcfac7-72be-434e-9f8a-c6d9b0adcddd, value = value-subscriptionsspec-topic-5cdcfac7-72be-434e-9f8a-c6d9b0adcddd),
    commitHandle = zio.kafka.consumer.internal.Runloop$$Lambda$2738/0x0000000801746580@7f8008aa,
    consumerGroupMetadata = Some(GroupMetadata(groupId = subscriptionsspec-group-17190f17-9b98-430f-955d-f2be5cfd379c, generationId = 1, memberId = subscriptionsspec-client-9dd96e9f-7788-45ca-8b46-0c3d7128eccf-883cd775-58a5-437f-9475-d8cc1b9fe01b, groupInstanceId = ))
  ), CommittableRecord(
    record = ConsumerRecord(topic = subscriptionsspec-topic-5cdcfac7-72be-434e-9f8a-c6d9b0adcddd, partition = 0, leaderEpoch = 0, offset = 0, CreateTime = 1689838595394, serialized key size = 64, serialized value size = 66, headers = RecordHeaders(headers = [], isReadOnly = false), key = key-subscriptionsspec-topic-5cdcfac7-72be-434e-9f8a-c6d9b0adcddd, value = value-subscriptionsspec-topic-5cdcfac7-72be-434e-9f8a-c6d9b0adcddd),
    commitHandle = zio.kafka.consumer.internal.Runloop$$Lambda$2738/0x0000000801746580@7f8008aa,
    consumerGroupMetadata = Some(GroupMetadata(groupId = subscriptionsspec-group-17190f17-9b98-430f-955d-f2be5cfd379c, generationId = 2, memberId = subscriptionsspec-client-9dd96e9f-7788-45ca-8b46-0c3d7128eccf-883cd775-58a5-437f-9475-d8cc1b9fe01b, groupInstanceId = ))
  ))
```
This is the same message from same topic-partition and same offset.

**Comment by guizmaii** [comment]
@myazinn So we're not consuming the message produced in `topic2` from the `readCount(topic1)(counter)`, right?
That's what I was worried about

**Comment by myazinn** [comment]
@guizmaii yep, you're right, apologies for confusion.
The message comes from a correct topic, the issue is that presence of `topic2` consumption might affect `topic1` consumption, even though they are supposed to be independent.

**Comment by guizmaii** [comment]
@myazinn Do you have the same issue when consuming topic2?

**Comment by myazinn** [comment]
@guizmaii in my test case it is impossible since I specifically take only one message from the stream.
If I update
```scala
      def readOne(topic: String) =
        plainStream(topic).take(1).runDrain
```
to
```scala
      def readOne(topic: String) =
        plainStream(topic).take(2).runDrain
```
and thus try to read two messages from `topic2`, then `topic2` stream will never end, duplicates in `topic1` stream will not appear, and test will pass as expected. Though in this case we'll have to change
```scala
 (readCount(topic1)(counter).fork *> readOne(topic2).zipPar(writeSingleTo(topic1, topic2)))
```
to
```scala
 (readCount(topic1)(counter).fork *> readOne(topic2).fork *> writeSingleTo(topic1, topic2))
```
to let test end, but it doesn't matter since this change alone doesn't fix or break test.

**Comment by erikvanoosten** [comment]
I do not understand why yet, but after adding some logging I can see that `writeSingleTo` is called twice.

**Comment by erikvanoosten** [comment]
Something is wrong with `ZIOSpecDefaultSlf4j`. Digging further...

**Comment by erikvanoosten** [comment]
@myazinn I am not even sure if you are using `ZIOSpecDefaultSlf4j`.
If you are, as a workaround you can add `@@withLiveRandom` or extend `ZIOSpecDefault` instead.

**Comment by erikvanoosten** [comment]
See also https://discord.com/channels/629491597070827530/630498701860929559/1132294623482617867

**Comment by erikvanoosten** [comment]
There was some double logging going on which let me on the wrong track. Will have to restart the research. Not sure if I have time for it soon.

**Comment by myazinn** [comment]
@erikvanoosten yes, I was using `ZIOSpecDefaultSlf4j`, since the suite in the description was written within `SubscriptionsSpec`. I wanted to just include it along with a fix, but I couldn't fix the issue myself and ended up copy-pasting it here. Not that it matters now since you've already found that there was another issue 🤔

**Comment by erikvanoosten** [comment]
@myazinn I found a bug in zio-kafka that causes this. I will need some more debugging to find out how to fix it.

**Comment by erikvanoosten** [comment]
@svroonland @guizmaii In case you want to look at this, I have added the unit test from the issue, and some logging to make the problem clear in branch https://github.com/zio/zio-kafka/tree/issue-988 file `ConsumerIssue988Spec.scala`.

**Comment by svroonland** [comment]
@erikvanoosten See my commit to that branch. It shows that after changing the subscription, a rebalance occurs. That resets the fetching to the last committed offsets.

So I think we can state that if you use multiple subscriptions and you change the subscription (implicitly by ending some streams), it will trigger the equivalent of a rebalance, which results in records being fetched from the last committed offset.

@myazinn Is this issue based on a real-life use case? Would committing the offset help in that case?

**Comment by myazinn** [comment]
@svroonland no, in my case it's not a real-life thing and happened in test.
I have a `real` service that reads from an `input` topic and produces messages to an `output` topic. The test looks roughly like this
```scala
for
  r   <- realService.start.fork
  _   <- produceToInput
  out <- readFromOutput
  _   <- r.interrupt
yield assertTrue(out == expected)
```
I was getting duplicates in `out` because I was using the same `Consumer` instance for both real service and a test method that was supposed to read messages from the `output` topic. Commiting the offset wouldn't really help (if we are talking about manual committing), since `realService` just doesn't have enough time to do it until another subscription joins and restarts all subscriptions.

**Comment by svroonland** [comment]
Thanks!

I'll add a note about this behavior to the documentation of sharing a Consumer for multiple subscriptions, but other than that I'm inclined to close this issue.
