### ISSUE TITLE
Accessor methods for AdminClient

### ISSUE THREAD

**Issue by RoccoMathijn** [zio/zio-kafka#991]
Would it make sense to have accessor methods for the `AdminClient` like there are for the `Consumer`? If so shall I try and provide a PR?

**Comment by guizmaii** [comment]
I'd prefer not as it's more code to maintain for us. Just use `ZIO.serviceWithZIO[AdminClient](_.methodCall)`

**Comment by RoccoMathijn** [comment]
That makes sense. Thanks 🙏
